assets:
  gradle.properties: yegor256/home#assets/polystat/gradle.properties
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install: |
  sudo docker run -v $(pwd)/src:/app/src -v $(pwd)/build:/app/build iammaxim/j2eo:latest bash build.sh
merge:
  script: |
    sudo docker run -v $(pwd)/src:/app/src -v $(pwd)/build:/app/build iammaxim/j2eo:latest bash build.sh
release:
  script: |-
    mv ../gradle.properties .
    ./gradlew publish --info -PmvnPublicationVersion=${tag}
