docker:
  as_root: true
assets:
  gradle.properties: yegor256/home#assets/polystat/gradle.properties
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install: |
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 E1DF1F24 3DD9F856
  apt-get install autoconf automake autopoint flex gperf graphviz help2man texinfo valgrind
  apt-get install -y m4
  wget http://ftp.gnu.org/gnu/bison/bison-3.8.tar.gz
  tar -zxvf bison-3.8.tar.gz
  cd bison-3.8
  ./configure
  make
  pwd
  ls -a .
  make install
  bison -V
  cd ..
  apt install -y openjdk-16-jdk
  ls -a /usr/lib/jvm/
  export JAVA_HOME=/usr/lib/jvm/java-16-openjdk-amd64
  echo $JAVA_HOME
  java -version
  ./gradlew build --info
merge:
  script: |
    ./gradlew build --info
release:
  script: |-
    git commit -am "${tag}"
    mv ../gradle.properties .
    ./gradlew build --info
#    ./gradlew build publish --info -PmvnPublicationVersion=${tag}
