assets:
  gradle.properties: yegor256/home#assets/polystat/gradle.properties
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install: |
  sudo apt install -y openjdk-16-jdk
  ls -a /usr/lib/jvm/
  sudo export JAVA_HOME=/usr/lib/jvm/openjdk-16-jdk
  echo $JAVA_HOME
  java -version
  ./gradlew build --info
merge:
  script: |
    ./gradlew build --info
release:
  script: |-
    git commit -am "${tag}"
    mv ../gradle.properties .
    ./gradlew build publish --info -PmvnPublicationVersion=${tag}
