assets:
  gradle.properties: yegor256/home#assets/polystat/gradle.properties
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install: |
  docker build -t polystat/j2eo:latest -f docker/Dockerfile .
  docker run -v src:/app/src -v build:/app/build polystat/j2eo:latest bash build.sh
merge:
  script: |
    docker build -t polystat/j2eo:latest -f docker/Dockerfile .
    docker run -v src:/app/src -v build:/app/build polystat/j2eo:latest bash build.sh
release:
  script: |-
    git commit -am "${tag}"
    mv ../gradle.properties .
    ./gradlew publish --info -PmvnPublicationVersion=${tag}
