assets:
  gradle.properties: yegor256/home#assets/polystat/gradle.properties
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
docker:
  image: "iammaxim/j2eo:latest"
  as_root: true
release:
  script: |-
    pwd
    ls -lha
    cp ../gradle.properties .
    chmod +x build.sh
    ./build.sh
