assets:
  gradle.properties: yegor256/home#assets/polystat/gradle.properties
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install:
  - "cat ../gradle.properties"
merge:
  script:
    - "cat ../gradle.properties"
release:
  script:
    - "cat ../gradle.properties"
    - "mv ../gradle.properties ."
    - "./gradlew publish --info -PmvnPublicationVersion=${tag}"
