name: Gradle Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  bison:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install flex
      - run: sudo apt-get install bison
  gradle:
    strategy:
      matrix:
        os: [
            ubuntu-latest,
            macos-latest,
            windows-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 16

      - uses: gradle/gradle-build-action@v1
        with:
          arguments: build

      - uses: gradle/gradle-build-action@v1
        with:
          arguments: test
